export const QUERIES = {
  CATALOG: {
    ITEMS: "ITEMS",
    ITEM: "ITEM",
    ITEM_SPECIFICATIONS: "ITEM_SPECIFICATIONS",
    SPECIFICATION_CATEGORIES: "SPECIFICATION_CATEGORIES",
    SPECIFICATION_CATEGORY: "SPECIFICATION_CATEGORY",
  },
  CORE: {
    COMPANIES: "COMPANIES",
  },
};
